title: Using an LDR to measure light
hero_image: images/banner.png
subtitle: rpi-python-ldr subtitle
description: rpi-python-ldr description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: LDR for light

